window.addEventListener("load", function () {
  const justDataArr = [
    {
      src: "images/new1.png",
      alt: "구로청년이룸",
      colorbox: "교육/강연",
      city: "",
      text: "[구로청년이룸] 취업을 즐기다! <취얼업 페스타> 참여자 모집",
      date: "D-21",
    },
    {
      src: "images/new2.png",
      alt: "스타아티스트",
      colorbox: "공모전",
      city: "",
      text: "[스타아티스트] 제1회 아담국제영화제 작품공모",
      date: "D-73",
    },
    {
      src: "images/new3.png",
      alt: "유어유니콘",
      colorbox: "인턴십",
      city: "서울 강남구",
      text: "[유어유니콘] 컨텐츠 및 퍼포먼스 마케팅 인턴",
      date: "D-12",
    },
    {
      src: "images/new4.png",
      alt: "네이버웹툰",
      colorbox: "인턴십",
      city: "경기 성남시",
      text: "[네이버웹툰] EU Webtoon 영상 디자이너",
      date: "오늘 마감",
    },
    {
      src: "images/new5.png",
      alt: "NAVER Cloud",
      colorbox: "인턴십",
      city: "경기 성남시",
      text: "[NAVER Cloud] SaaS(클라우드형 협업툴) Contents Development",
      date: "D-1",
    },
    {
      src: "images/new6.png",
      alt: "PTKOREA",
      colorbox: "인턴십",
      city: "서울 강남구",
      text: "[PTKOREA] 디지털 캠페인 기획 및 SNS 운영 보조",
      date: "D-11",
    },
    {
      src: "images/new7.png",
      alt: "라이카카메라코리아",
      colorbox: "인턴십",
      city: "서울 강남구",
      text: "[라이카카메라코리아] Sales Intern",
      date: "D-7",
    },
    {
      src: "images/new8.png",
      alt: "당근마켓",
      colorbox: "인턴십",
      city: "서울 서초구",
      text: "[당근마켓] FP&A Intern",
      date: "D-5",
    },
  ];
});
